name: 'check terraform format&validate'

on:
  push:
    branches:
    - main
    - feature/*

jobs:
  terraform_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: cd infra;terraform fmt -check -diff

  terraform_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: cd infra;terraform init -backend=false;terraform validate
