name: CI

on:
  push:
    branches:
    - main
    - feature/*

jobs:
  terraform_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: cd infra;terraform fmt -check -diff

  terraform_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: cd infra;terraform init -backend=false;terraform validate

  terraform_plan:
    runs-on: ubuntu-latest
    env:
      STATE_BUCKET= ${{ var.STATE_BUCKET}}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: cd infra;terraform init -backend-config="bucket=$STATE_BUCKET";terraform plan
