name: CI


on:
  workflow_dispatch:
  push:
    branches:
    - main
    - feature/*
    tags:
      - '*'
permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  IAM_ROLE: GitHubAction

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{env.IAM_ROLE}}
      - name: Format
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: 1.8.5
          tg_version: 0.59.6
          tg_dir: infra/dev
          tg_command: fmt -check -diff

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{env.IAM_ROLE}}
      - name: Validate
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: 1.8.5
          tg_version: 0.59.6
          tg_dir: infra/dev
          tg_command: validate

  plan:
    needs:
      - format
      - validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{env.IAM_ROLE}}
      - name: Plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: 1.8.5
          tg_version: 0.59.6
          tg_dir: infra/dev
          tg_command: plan
  

  apply:
    needs: plan
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{env.IAM_ROLE}}
      - name: Apply
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: 1.8.5
          tg_version: 0.59.6
          tg_dir: infra/dev
          tg_command: apply -auto-approve

  plan_prod:
    if: github.ref_type == 'tag'
    needs:
      - format
      - validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{env.IAM_ROLE}}
      - name: Plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: 1.8.5
          tg_version: 0.59.6
          tg_dir: infra/prod
          tg_command: plan


  apply_prod:
    needs: plan_prod
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{env.IAM_ROLE}}
      - name: Apply
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: 1.8.5
          tg_version: 0.59.6
          tg_dir: infra/prod
          tg_command: apply -auto-approve
