name: CI

on:
  push:
    branches:
    - main
    - feature/*
    tags:
      - '*'

jobs:
  terraform_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: cd infra;terraform fmt -check -diff

  terraform_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: cd infra;terraform init -backend=false;terraform validate

  terraform_plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      STATE_BUCKET: ${{ vars.STATE_BUCKET }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/GithubAction
      - run: cd infra;terraform init -backend-config="bucket=$STATE_BUCKET";terraform plan
  

  terraform_apply:
    needs: terraform_plan
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    env:
      STATE_BUCKET: ${{ vars.STATE_BUCKET }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/GithubAction
      - run: cd infra;terraform init -backend-config="bucket=$STATE_BUCKET";terraform apply -auto-approve

  terraform_plan_prod:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      STATE_BUCKET: ${{ vars.STATE_BUCKET }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/GithubAction
      - run: cd infra;terraform init -backend-config="bucket=$STATE_BUCKET";terraform workspace select -or-create prod;terraform plan -var="env=prod"

  terraform_apply_prod:
    needs: terraform_plan_prod
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write
      contents: read
    env:
      STATE_BUCKET: ${{ vars.STATE_BUCKET }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/GithubAction
      - run: |
          cd infra;
          terraform init -backend-config="bucket=$STATE_BUCKET";
          terraform workspace select -or-create prod;
          terraform apply -var="env=prod" -auto-approve

